.catalog:
  name: "Rancher Logging"
  version: "v0.2.0"
  description: "Rancher Logging Collector"
  questions:
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "elasticsearch/elasticsearch-clients"
    - variable: "log_vol_pattern"
      description: "Pattern of logging volumes name"
      label: "Volume Pattern"
      type: "string"
      required: true
      default: "rancher-logging*"
    - variable: "log_file_pattern"
      description: "Pattern of logging files name"
      label: "File Pattern"
      type: "string"
      required: true
      default: "*.log"

logging-helper:
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 9898
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreate
    request_line: GET "/healthcheck" "HTTP/1.0"
    reinitializing_timeout: 60000
